name: CI
on:
  push:
    paths:
      - "src/**"
      - "test/**"
      - ".github/workflows/**"
      - "package.json"
      - "pnpm-lock.yaml"
    branches:
      - "**"
  pull_request:
    paths:
      - "src/**"
      - "test/**"
      - ".github/workflows/**"
      - "package.json"
      - "pnpm-lock.yaml"
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
            - args: [typescript]
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Test and building
        run: pnpm run ci
